### ISSUE TITLE
运行时报错栈溢出

### ISSUE THREAD

**Issue by machuanhu** [zhihu/ZhiLight#13]
zhilight) root@7e3f0f7cd7c4f4a9:~/ZhiLight# python -m zhilight.server.openai.entrypoints.api_server --model-path /workspace/heavenly-goat-v8-model
INFO 12-15 11:06:57 api_server.py:152] ZhiLight OpenAI-Compatible Server version 0.4.8.
INFO 12-15 11:06:57 api_server.py:160] args: Namespace(host='0.0.0.0', port=8080, api_key='*', served_model_name=None, response_role='assistant', uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], zhilight_version=None, environ=[], pip=[], model_path='/workspace/heavenly-goat-v8-model', max_model_len=8192, disable_flash_attention=False, enable_cpm_chat=False, disable_tensor_parallel=False, enable_prefix_caching=False, disable_log_stats=False, quantization=None, dyn_max_batch_size=8, dyn_max_beam_size=4, ignore_eos=False, disable_log_requests=False, max_log_len=None)
INFO 12-15 11:06:57 llm_engine.py:20] engine config => EngineConfig(model_path='/workspace/heavenly-goat-v8-model', model_file='/workspace/heavenly-goat-v8-model/model-00001-of-00006.safetensors', vocab_file='/workspace/heavenly-goat-v8-model/vocabs.txt', is_cpm_directory_struct=False, use_safetensors=True, model_config={'_name_or_path': 'DeverDever/heavenly-goat-v8', 'architectures': ['MistralModel'], 'attention_dropout': 0.0, 'bos_token_id': 1, 'eos_token_id': 32000, 'head_dim': 128, 'hidden_act': 'silu', 'hidden_size': 4096, 'initializer_range': 0.02, 'intermediate_size': 14336, 'max_position_embeddings': 32768, 'model_type': 'mistral', 'num_attention_heads': 32, 'num_hidden_layers': 32, 'num_key_value_heads': 8, 'rms_norm_eps': 1e-05, 'rope_theta': 10000.0, 'sliding_window': 4096, 'tie_word_embeddings': False, 'torch_dtype': 'float32', 'transformers_version': '4.47.0', 'use_cache': False, 'vocab_size': 32002, 'num_layers': 32, 'dim_model': 4096, 'num_heads': 32, 'num_kv_heads': 8, 'max_token': 32768, 'dim_ff': 14336, 'eps': 1e-05, 'activate_fn': 'silu', 'bfloat16': False, 'new_vocab': False}, dyn_batch_config=DynamicBatchConfig(max_batch=8, max_beam_size=4, task_queue_size=8, max_total_token=8192, seed=0, bos_id=0, eos_id=2, nccl=-1, rag_buffer=True), quant_config={'type': <QuantType.NoQuant: 0>}, memory_limit=0, enable_tensor_parallel=True, is_chatml=False, max_model_len=8192)
[DEV]Config: HIGH_PRECISION=1; DUAL_STREAM=None; CPM_FUSE_QKV=1; CPM_FUSE_FF_IN=1; REDUCE_TP_INT8_THRES=None; W4_INT8_ALGO=None; W4_FP8_ALGO=None
dist_config: parallel=True
********* world_size=1, nccl_version=21505 *********
*** stack smashing detected ***: terminated
Aborted (core dumped)

**Comment by spetrel** [comment]
what GPU do you use ?

**Comment by machuanhu** [comment]
> what GPU do you use ?

4090

**Comment by spetrel** [comment]
'torch_dtype': 'float32' is not supported. Only float16, bfloat16 or GPTQ/AWQ models.
