### ISSUE TITLE
[QUESTION] About all-reduce overlap

### ISSUE THREAD

**Issue by ZhongYingMatrix** [zhihu/ZhiLight#8]
Thx for ur wonderful work! I am very interested in your method of `Encode and all-reduce overlap, we named "dual streams"`. Could you provide a general explanation of this technical approach?

**Comment by unix1986** [comment]
@ZhongYingMatrix Thank you for your attention. Dual-Streams employing two CUDA streams, one designated for All-Reduce operations and the other for Prefill computations. The Prefill process is segmented into multiple chunks based on tokens. The approach involves computing one chunk initially, followed by an All-Reduce step, and then proceeding to compute the next chunk in parallel, iterating through this cycle until completion. This feature is contributed by my colleague @spetrel .

**Comment by spetrel** [comment]
We do "chunks" only for prompt encoding computation, the KV cache is "continuous" as one piece.

**Comment by ZhongYingMatrix** [comment]
@spetrel Is it chunked before or after QKV projection? I suppose that any query chunk should refer to all of the key/value chunks.

**Comment by spetrel** [comment]
before, at the input of block layer. Yes, all query chunks refer to the whole KV cache. cuda events is used to synchronize between chunks attentions to make sure previous chunk attention get done before next chunk attention.
